### ISSUE TITLE
ReferenceError error: Gallery is not defined

### ISSUE THREAD

**Issue by ruggeroland** [obigroup/magento-configurable-simple#25]
Hello, I have a configurable product that contains 3 simple products. When I change the color I see this "ReferenceError error: Gallery is not defined"
I wish they would change the thumb when I change the color of the simple product.
can you help me?

**Comment by Quazz** [comment]
Problem seems to originate from here:

https://github.com/organicinternet/magento-configurable-simple/pull/184/commits/7321776d6c97e96f4cf120b33cf25d57fe5e614c

It assumes you make use of Galleria.js, but if you don't use this whatsoever it will throw the error you experience.

Replace the javascript file with this older one:

https://github.com/jhuriez/magento-configurable-simple/blob/17225b346855eecad9e4bda7cf163db5b2bac890/skin/frontend/base/default/js/scp_product_extension.js

**Comment by ruggeroland** [comment]
ok thank you
