### ISSUE TITLE
Call to a member function isAvailable() on a non-object

### ISSUE THREAD

**Issue by renini** [obigroup/magento-configurable-simple#6]
Getting a error 500 with this php error when viewing a configurable product in the store.

PHP Fatal error:  Call to a member function isAvailable() on a non-object in /app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Block/Product/View/Type/Configurable.php on line 114

This is with PHP 5.6.0beta4 and Magento 1.9.1 CE.
Any idea on how to patch/fix this?

**Comment by jwittorf** [comment]
Try this, worked for me:

```

(...)

        // Prevent Issue 6 start 1
        $childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $p);
        Mage::register('child_product', $childProducts);
        // Prevent Issue 6 end 1

        if ($bShowProductAlerts && !Mage::registry('child_product')->isAvailable()) {
            $oAlertBlock = $this->getLayout()->createBlock('productalert/product_view')
                    ->setTemplate('productalert/product/view.phtml')
                    ->setSignupUrl(Mage::helper('productalert')->setProduct(Mage::registry('child_product'))->getSaveUrl('stock'));;
            $config["alertHtml"] = $oAlertBlock->toHtml();
        }

        if (Mage::getStoreConfig('SCP_options/product_page/change_image')) {
            if (Mage::getStoreConfig('SCP_options/product_page/change_image_fancy')) {
                $childBlock = $this->getLayout()->createBlock('catalog/product_view_media');
                $config["imageZoomer"] = $childBlock->setTemplate('catalog/product/view/media.phtml')
                    ->setProduct($this->getProduct())
                    ->toHtml();
            }
        }

        if (Mage::getStoreConfig('SCP_options/product_page/show_price_ranges_in_options')) {
            $config['showPriceRangesInOptions'] = true;
            $config['rangeToLabel'] = $this->__('to');
        }

        // Prevent Issue 6 start 2
        Mage::unregister('child_product');
        // Prevent Issue 6 end 2

(...)

```

**Comment by westaussie** [comment]
Hi,

I can confirm this as well.

Running PHP 5.3.29 and Magento CE 1.9.0.1.

The error I have is:

var spConfig = new Product.Config(<br />
<b>Fatal error</b>:  Call to a member function isAvailable() on a non-object in <b>/home/safety/public_html/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Block/Product/View/Type/Configurable.php</b> on line <b>126</b>

Line 126 in my Configurable.php is:

if ($bShowProductAlerts && !Mage::registry('child_product')->isAvailable()) {

Tried the above from @jwittorf with no success.

**Comment by jwittorf** [comment]
Forget my last comment, I've commented out the following code part:

```

        // Prevent Issue 6 start
        /*
        $bShowProductAlerts = Mage::getStoreConfig(Mage_ProductAlert_Model_Observer::XML_PATH_STOCK_ALLOW);
        if ($bShowProductAlerts && !Mage::registry('child_product')->isAvailable()) {
            $oAlertBlock = $this->getLayout()->createBlock('productalert/product_view')
                    ->setTemplate('productalert/product/view.phtml')
                    ->setSignupUrl(Mage::helper('productalert')->setProduct(Mage::registry('child_product'))->getSaveUrl('stock'));;
            $config["alertHtml"] = $oAlertBlock->toHtml();
        }
        */
        // Prevent Issue 6 end

        if (Mage::getStoreConfig('SCP_options/product_page/change_image')) {
            if (Mage::getStoreConfig('SCP_options/product_page/change_image_fancy')) {
                $childBlock = $this->getLayout()->createBlock('catalog/product_view_media');
                $config["imageZoomer"] = $childBlock->setTemplate('catalog/product/view/media.phtml')
                    ->setProduct($this->getProduct())
                    ->toHtml();
            }
        }

```

This is just a hotfix and still needs to be improved.

Just for a note, at this point of code we're not in a foreach-loop but the call is trying to access data from just one of the products. There is no "isAvailable" for ALL the simple products. I think we'd need a small loop right here that'll return the state for each associated product or something like that for setting the `$config["alertHtml"]`. Or am I getting it wrong?

Hope somebody get's the point I'm trying to make and can fix this, I'm more into frontend development ...

**Comment by westaussie** [comment]
Thanks @jwittorf ... can confirm commenting out that block works for me ... note it is the second $bShowProductAlerts = block and not the first one ;-) No other side effects noticed so far.
